-- MySQL Script generated by MySQL Workbench
-- Tue May 14 22:28:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_ahorros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_ahorros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_ahorros` DEFAULT CHARACTER SET utf8 ;
USE `app_ahorros` ;

-- -----------------------------------------------------
-- Table `app_ahorros`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `numero_de_identificacion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`tipos_tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`tipos_tarjetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`asociaciones_tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`asociaciones_tarjetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asociacion` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`tarjetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(18) NOT NULL,
  `id_tipo_tarjeta` INT NOT NULL,
  `id_asociacion_tarjeta` INT NOT NULL,
  `cuota_manejo` INT NULL,
  `fecha_cuota_manejo` VARCHAR(45) NULL,
  `nombre_banco` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarjetas_tipo_tarjeta_idx` (`id_tipo_tarjeta` ASC) VISIBLE,
  INDEX `fk_tarjetas_asociacion_tarjeta1_idx` (`id_asociacion_tarjeta` ASC) VISIBLE,
  INDEX `fk_tarjetas_estados1_idx` (`id_estado` ASC) VISIBLE,
  INDEX `fk_tarjetas_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tarjetas_tipo_tarjeta`
    FOREIGN KEY (`id_tipo_tarjeta`)
    REFERENCES `app_ahorros`.`tipos_tarjetas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarjetas_asociacion_tarjeta1`
    FOREIGN KEY (`id_asociacion_tarjeta`)
    REFERENCES `app_ahorros`.`asociaciones_tarjetas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarjetas_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `app_ahorros`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarjetas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `app_ahorros`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`tipos_dineros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`tipos_dineros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`tipos_periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`tipos_periodos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `periodo` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`gastos_y_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`gastos_y_ingresos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `id_tipo_periodo` INT NOT NULL,
  `id_tipo_dinero` INT NOT NULL,
  `id_tarjeta` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingresos_tarjetas1_idx` (`id_tarjeta` ASC) VISIBLE,
  INDEX `fk_gastos_y_ingresos_tipo_dinero1_idx` (`id_tipo_dinero` ASC) VISIBLE,
  INDEX `fk_gastos_y_ingresos_estados1_idx` (`id_estado` ASC) VISIBLE,
  INDEX `fk_gastos_y_ingresos_tipos_periodos1_idx` (`id_tipo_periodo` ASC) VISIBLE,
  CONSTRAINT `fk_ingresos_tarjetas1`
    FOREIGN KEY (`id_tarjeta`)
    REFERENCES `app_ahorros`.`tarjetas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_y_ingresos_tipo_dinero1`
    FOREIGN KEY (`id_tipo_dinero`)
    REFERENCES `app_ahorros`.`tipos_dineros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_y_ingresos_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `app_ahorros`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_y_ingresos_tipos_periodos1`
    FOREIGN KEY (`id_tipo_periodo`)
    REFERENCES `app_ahorros`.`tipos_periodos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`metas_ahorros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`metas_ahorros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `valor` INT NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  `fecha_final` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_metas_ahorros_estados1_idx` (`id_estado` ASC) VISIBLE,
  INDEX `fk_metas_ahorros_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_metas_ahorros_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `app_ahorros`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metas_ahorros_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `app_ahorros`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
