-- MySQL Script generated by MySQL Workbench
-- Wed May 15 20:37:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_ahorros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_ahorros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_ahorros` DEFAULT CHARACTER SET utf8 ;
USE `app_ahorros` ;

-- -----------------------------------------------------
-- Table `app_ahorros`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `numero_de_identificacion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`tipos_tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`tipos_tarjetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`asociaciones_tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`asociaciones_tarjetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asociacion` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`tarjetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(18) NOT NULL,
  `id_tipo_tarjeta` INT NOT NULL,
  `id_asociacion_tarjeta` INT NOT NULL,
  `cuota_manejo` INT NULL,
  `fecha_cuota_manejo` VARCHAR(45) NULL,
  `nombre_banco` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`tipos_dineros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`tipos_dineros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`tipos_periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`tipos_periodos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `periodo` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`gastos_y_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`gastos_y_ingresos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `id_tipo_periodo` INT NOT NULL,
  `id_tipo_dinero` INT NOT NULL,
  `id_tarjeta` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_ahorros`.`metas_ahorros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_ahorros`.`metas_ahorros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `valor` INT NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  `fecha_final` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
